; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = ./boards
extra_configs = upload_params.ini
; examples
; src_dir = ./examples/serial
; src_dir = ./examples/mac
; src_dir = ./examples/breathing-light
; src_dir = ./examples/task-stack-size
; src_dir = ./examples/dev-mode
; src_dir = ./examples/battery-voltage
; src_dir = ./examples/touch-CST816T

; src_dir = ./examples/wifi-ap
; src_dir = ./examples/ota
; src_dir = ./examples/ota-telnet
; src_dir = ./examples/ota-webserver
; src_dir = ./examples/ota-manager-rtos

; disable Serial, if its unused otherwise some features work only with an open monitor-port
; e.g. the breathlight is not working
; -DARDUINO_USB_CDC_ON_BOOT=0 
[env]
build_flags = 
	'-DPIOENV="${PIOENV}"'
	-DSERIAL_DEBUG
	-DCORE_DEBUG_LEVEL=5
	-DARDUINO_USB_CDC_ON_BOOT=1
	-Wno-unused-variable
	-Wno-unused-but-set-variable
	-Wunreachable-code
extra_scripts = pre:extra_script.py
framework = arduino
lib_deps = 
monitor_speed = 115200
; uncomment when using multiple ESPs, default is auto
; upload_port = /dev/cu.usbmodem14201
monitor_port = /dev/cu.usbmodem14201
platform = espressif32
upload_speed = 921600

[extra]
build_flags_psram =
lib_deps_builtin =
	SPI
	Wire
lib_deps_external =
	lennarthennigs/ESP Telnet @ ^2.2.1
  ; moononournation/GFX Library for Arduino @ ^1.6.0

[esp32]
build_flags = 
	${env.build_flags}
lib_deps = 
	${env.lib_deps}
	${extra.lib_deps_builtin}
	${extra.lib_deps_external}

[esp32c6]
build_flags = 
	${env.build_flags}
lib_deps =
	${env.lib_deps}
	${extra.lib_deps_builtin}
	${extra.lib_deps_external}
;; platformio stable
; platform = espressif32
;; platformio develop
; platform = https://github.com/platformio/platform-espressif32.git
;; community stable with Arduino 3.x
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
;; community develop with Arduino 3.x
; platform = https://github.com/pioarduino/platform-espressif32.git#develop
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13-1/platform-espressif32.zip
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

[esp32c6-ota]
upload_speed = 2000000
upload_protocol = espota
; change upload_port after connected to your network instead of the ESP AP
; upload_port = 192.168.4.1
upload_port = 192.168.50.105

[env:esp32-c6-n4]
extends = esp32c6
board = esp32-c6-n4

[env:esp32-c6-n4-ota]
extends = env:esp32-c6-n4
upload_speed = ${esp32c6-ota.upload_speed}
upload_protocol = ${esp32c6-ota.upload_protocol}
upload_port = ${esp32c6-ota.upload_port}
